-- sql statment start when database start
-- MySQL Script generated by MySQL Workbench
-- Tue May  8 21:59:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myapp` DEFAULT CHARACTER SET utf8 ;
USE `myapp` ;

-- -----------------------------------------------------
-- Table `myapp`.`timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`timeline` (
  `timeline_id` INT NOT NULL AUTO_INCREMENT,
  `timeline_userid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`timeline_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`text` (
  `text_id` INT NOT NULL AUTO_INCREMENT,
  `text_title` VARCHAR(100) NOT NULL,
  `text_article` VARCHAR(500) NOT NULL,
  `timeline_id` INT NOT NULL,
  PRIMARY KEY (`text_id`),
  INDEX `fk_text_timeline_idx` (`timeline_id` ASC),
  CONSTRAINT `fk_text_timeline`
    FOREIGN KEY (`timeline_id`)
    REFERENCES `myapp`.`timeline` (`timeline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
